language: c
os: linux
dist: focal
services:
  - docker
addons:
  apt:
    packages:
      - docker.io
before_script:
  - if [[ $DISTRO = "centos" ]]; then export COMPILE_ONLY="1"; fi
  - export DC_FILE="docker-compose.yml"
  - if [[ $DISTRO = "ssl_server" ]]; then export DC_FILE="docker/docker-compose-ssl-server.yml"; fi
  - if [[ $DISTRO = "unix_socket" ]]; then export DC_FILE="docker/docker-compose-unix-socket.yml"; fi
  - docker-compose -f $DC_FILE pull
  - docker-compose -f $DC_FILE build
  - docker-compose -f $DC_FILE up -d
  - docker ps
after_script:
  - docker-compose -f $DC_FILE down
script:
  - |
    if [[ $DISTRO = "ssl_server" ]]; then
      sleep 20
      docker-compose -f $DC_FILE exec -e RELEASE="1" -e CONFIG_FILE="libnss-maria.conf" -e EXAMPLE_SET="ssl" -e TEST_USE_SSL="1" -e CLIENT_FILE="client.cnf" sys sh -c "/home/libnss-maria/scripts/compile_and_test.sh"
    elif [[ $DISTRO = "unix_socket" ]]; then
      docker-compose -f $DC_FILE exec -e RELEASE="1" -e CONFIG_FILE="libnss-maria.conf" -e EXAMPLE_SET="unix_socket" sys sh -c "/home/libnss-maria/scripts/compile_and_test.sh"
    else
      sleep 20
      docker-compose -f $DC_FILE exec -e RELEASE="1" -e CONFIG_FILE="libnss-maria-docker.conf" -e COMPILE_ONLY=$COMPILE_ONLY sys sh -c "/home/libnss-maria/scripts/compile_and_test.sh"
    fi
env:
  - DISTRO="archlinux"
  - DISTRO="centos"
  - DISTRO="debian"
  - DISTRO="fedora"
  - DISTRO="ssl_server"
  - DISTRO="ubuntu"
  - DISTRO="ubuntu-lts"
  - DISTRO="unix_socket"
