FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y build-essential cmake libmariadb-dev libconfig-dev syslog-ng-dev bats \
syslog-ng mariadb-client libconfig9 ruby pkg-config
