FROM debian:bullseye
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y build-essential cmake libmariadb-dev libconfig-dev syslog-ng-dev bats \
syslog-ng mariadb-client libconfig9 mariadb-server ruby pkg-config
ENTRYPOINT ["/home/libnss-maria/docker/unix_socket_entrypoint.sh"]
